USE zomato;

#1. Which delivery partner has the highest order volume?
SELECT partner_name,count(order_id) as 'Volume' FROM delivery_partner as d
join orders as o
on d.partner_id=o.partner_id
GROUP BY partner_name
ORDER BY Volume DESC
LIMIT 1;

#2. What is the total sales revenue per restaurant?
SELECT r_name ,sum(amount) as 'Revenue' FROM restaurants as r
join orders as o
ON r.r_id=o.r_id
GROUP BY r_name
ORDER BY Revenue DESC;

#3. What are the top-selling food items?
SELECT * FROM food;
SELECT T.f_name,COUNT(T.order_id) as 'Top sell food' FROM (
SELECT o.order_id,f.f_name,f.f_id,o.amount FROM orders as o
JOIN order_details  as od ON O.order_id=od.order_id 
JOIN food  as f ON OD.f_id=f.f_id )T
GROUP BY T.f_name
ORDER BY COUNT(T.order_id) DESC
LIMIT 5;


#4. What is the average delivery rating by partner?
SELECT dp.partner_name,AVG(o.delivery_rating) as 'Avg_rating' FROM orders as o
JOIN delivery_partner as dp
ON o.partner_id=dp.partner_id
GROUP BY dp.partner_name
ORDER BY Avg_rating DESC;

#5. Which restaurants have the highest customer satisfaction based on ratings?
SELECT r.r_name,ROUND(AVG(o.restaurant_rating),2) as 'Avg_rating' FROM restaurants as r
JOIN orders as o
ON r.r_id=o.r_id
GROUP BY r.r_name
ORDER BY Avg_rating DESC
LIMIT 1;

#6. What is the average order value for each restaurant?
SELECT r.r_name,Avg(o.amount) as 'Avg_value' FROM orders as o
JOIN restaurants as r 
ON r.r_id=o.r_id
GROUP BY r.r_name
ORDER BY Avg_value DESC;


#7. What is the total number of orders by food type?
SELECT f.type,sum(o.order_id) as 'count_order',RANK() OVER(ORDER BY sum(o.order_id) desc) FROM food AS f
JOIN order_details as od
ON f.f_id=od.f_id
JOIN orders as o
ON od.order_id=o.order_id
GROUP BY f.type;

#8. Which food items have the highest average rating?
SELECT f.f_name,AVG(o.delivery_rating) AS 'AvgRating' FROM food AS f
JOIN order_details as od
ON f.f_id=od.f_id
JOIN orders as o
ON od.order_id=o.order_id
GROUP BY f.f_name
ORDER BY AvgRating DESC ;

#9. What is the average delivery time per restaurant?
SELECT r.r_name,AVG(o.delivery_time) AS 'AvgDeliveryTime' FROM orders as o
JOIN restaurants as r
ON r.r_id=o.r_id
GROUP BY r.r_name
ORDER BY AvgDeliveryTime ASC;


#10. What are the peak times for orders based on delivery date and time?
#Unavailabe data source

#11. What is the total revenue generated by each delivery partner?
SELECT dp.partner_name,sum(o.amount) as 'Revenue' FROM orders as o
JOIN delivery_partner as dp
ON dp.partner_id=o.partner_id
GROUP BY dp.partner_name
ORDER BY Revenue DESC;

#12. Which menu items are being ordered together the most?
SELECT od1.f_id AS food_id_1, od2.f_id AS food_id_2, COUNT(*) AS order_pair_count
FROM order_details od1
JOIN order_details od2 ON od1.order_id = od2.order_id AND od1.f_id != od2.f_id
GROUP BY food_id_1, food_id_2
ORDER BY order_pair_count DESC
LIMIT 5;

#13. What is the most popular cuisine across all restaurants?
SELECT r.cuisine,SUM(o.amount) as 'TOTAL' FROM restaurants as r
JOIN orders as o
ON o.r_id=r.r_id
GROUP BY r.cuisine
ORDER BY TOTAL DESC;


#14. What is the monthly revenue trend for each restaurant?
SELECT MONTHNAME(date) as 'MonthName',r.r_name,SUM(o.amount) as 'Revenue'  FROM orders AS o
JOIN restaurants AS r
ON r.r_id=o.r_id
GROUP BY MonthName ,r.r_name
ORDER BY MonthName DESC,Revenue desc;

#15. What is the most ordered food item during a specific time of day 
#(e.g., lunch or dinner)?
#Unavailable data source

#16. What is the average delivery rating by order amount?
select amount,AVG(delivery_rating) as 'AVGR' from orders
group by amount
ORDER BY amount DESC;

#17. What is the repeat customer rate for each restaurant?

SELECT r.r_name,
(count(distinct o.user_id)/count(o.user_id))*100 as 'RepeatRate'
 FROM restaurants as r
JOIN orders as o
ON r.r_id=o.r_id
GROUP BY r.r_name;


#18. Which food items have the highest return on investment (ROI) based on price and sales?

SELECT f.f_name,SUM(o.amount-m.price) as 'TotalReturn' FROM orders as o
JOIN menu as m
ON m.r_id=o.r_id
JOIN food as f
on m.f_id=f.f_id
GROUP BY f.f_name
ORDER BY TotalReturn DESC;


#19. What are the most common delivery times across different restaurants?
SELECT r.r_name , AVG(o.delivery_time) AS 'Average' FROM orders as o
JOIN restaurants as r
on r.r_id= o.r_id
GROUP BY r.r_name;


#20. What is the average number of items ordered per order by restaurant?
SELECT od.order_id,r.r_name,COUNT(od.id) as 'CountPerOrder' FROM orders as o
JOIN order_details as od
ON o.order_id=od.order_id
JOIN restaurants as r
ON r.r_id=o.r_id
GROUP BY o.order_id,r.r_name;

#21. What is the percentage of orders that were delivered late by each delivery partner?
/*SELECT * FROM orders AS O
JOIN restaurants AS r
ON o.r_id=r.r_id; */
#Data source not Available

#22. What is the average delivery time during peak vs off-peak hours?
SELECT  
CASE 
WHEN o.delivery_time BETWEEN 11 AND 13  THEN "Peak_Hours"
WHEN o.delivery_time BETWEEN 18 AND 21 THEN "Peak_Hours"
ELSE "Off_Peak_Hours"
END AS Time_Period,
Avg(o.delivery_time) as 'AverageTime'
FROM orders as o
GROUP BY Time_Period;
#Due to some byes in data this is not right analysis for avg time for time period but this query 
# help you in practisize the case operator concept

/*23. What is the customer lifetime value (CLV) for 
each restaurant based on the total amount spent per customer? */
SELECT r.r_name,o.user_id,SUM(o.amount) as 'Customer_Lifetime_Value' FROM orders as o
JOIN restaurants as r
ON r.r_id=o.r_id
GROUP BY r.r_name,o.user_id
ORDER BY Customer_Lifetime_Value DESC;


#24. What is the correlation between restaurant rating and delivery rating?
SELECT r.r_name,AVG(o.delivery_rating) as 'AvgDeliveryRating',
AVG(o.restaurant_rating) AS 'AvgRestaurantRating'
 FROM orders AS o
JOIN restaurants AS r
GROUP BY r.r_name
ORDER BY AvgDeliveryRating DESC,AvgRestaurantRating DESC;

#25. Which food items have the highest variance in sales across different restaurants?
SELECT f.f_name, VARIANCE(m.price) AS 'price_variance'
FROM food  AS f
JOIN menu  AS  m ON f.f_id = m.f_id
GROUP BY f.f_name
ORDER BY price_variance DESC;

#26. How do sales vary based on day of the week?
SELECT DAYNAME(date) AS 'DAYS' ,SUM(AMOUNT) AS 'TotalSales' FROM orders
GROUP BY DAYS
ORDER BY TotalSales DESC;

#30. Which restaurant has the highest average food price?
SELECT r_id,avg(price) as 'AvgPrice' FROM menu
GROUP BY r_id
ORDER BY AvgPrice DESC;






